version: 0.0
os: linux

files:
  - source: build/
    destination: /tmp/react-build

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/upload-to-s3.sh
      timeout: 300
      runas: ec2-user
